### ISSUE TITLE
User can view and edit their account settings

### ISSUE THREAD

**Issue by kimberly-bird** [IndomitableIbises/Bangazon-Sprint-3#14]
- [x] **Given** the user is authenticated
- [x] **When** the user clicks on "my account" in the nav
- [x] **Then** the user will be taken to account view

The account view will include:
- First Name
- Last Name
- Address
- Phone Number
- Payment Options
- Order History
--------------------------------------------------

- [x] **Given** the user is on the Account View
- [x] **When** the user clicks "edit account"
- [x] **Then** the user will be presented with a pre-populated form to edit their address, phone number, and last name
-----------------
- [x] **Given** the user has completed the form with valid information
- [x] **When** the user clicks "update"
- [x] **Then** the information will update in the database, and in the account view

**Comment by paulzimmclay** [comment]
- [ ] Set profile creation on login OR allow set to NULL
- [ ] Get update working for profile model fields

**Comment by paulzimmclay** [comment]
Ended up prompting user to create profile on registration because things got complicated with creating the profile model for the user after user creation.
